import {useState} from "react";
import {api} from "../api/client";
import type {Shipment} from "../api/types";
import {eur} from "../lib";
export function ActualOutcome({shipment:s,onChange}:{shipment:Shipment;onChange:()=>void}){
 const [depart,setDepart]=useState(""),[arrival,setArrival]=useState(""),[cost,setCost]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(){setBusy(true);setError("");try{await api.saveOutcome(s.id,{actual_departure:new Date(depart).toISOString(),actual_arrival:new Date(arrival).toISOString(),actual_cost_eur:Number(cost)});onChange()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <section className="actual-outcome"><h3>Actual delivery results {s.data_kind==="demo"&&<span className="mini">DEMO · excluded from metrics</span>}</h3>{s.actual&&<div className="benchmark-values"><span>Arrival error<b>{s.actual.arrival_error_minutes>=0?"+":""}{s.actual.arrival_error_minutes} min</b></span><span>Actual cost difference<b>{eur(s.actual.cost_error_eur)}</b></span><span>Deadline<b>{s.actual.on_time===null?"Not supplied":s.actual.on_time?"Met":"Missed"}</b></span></div>}{error&&<div role="alert" className="notice notice--warn">{error}</div>}{s.status!=="DELIVERED"?<button className="btn btn--sm btn--ghost" disabled={busy||!s.approved_at} onClick={async()=>{setBusy(true);try{await api.setStatus(s.id,"DELIVERED");onChange()}catch(e){setError(String(e))}finally{setBusy(false)}}}>Mark delivered to record actuals</button>:<form onSubmit={e=>{e.preventDefault();void save()}}><div className="service-fields"><label>Actual departure · device local<input required type="datetime-local" value={depart} onChange={e=>setDepart(e.target.value)}/></label><label>Actual arrival · device local<input required type="datetime-local" value={arrival} onChange={e=>setArrival(e.target.value)}/></label><label>Actual transport cost · €<input required min={0} step="0.01" type="number" value={cost} onChange={e=>setCost(e.target.value)}/></label></div><button className="btn btn--sm" disabled={busy||!s.approved_at}>Save actual results</button></form>}<p className="fineprint">Compared with the manager-approved snapshot. Negative arrival error means earlier arrival; negative cost difference means lower cost. Record measured values only.</p></section>
}
