import {useEffect,useState} from "react";
import {api} from "../api/client";
import type {NetNode,Service} from "../api/types";
const DAYS=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export function ServiceSettings({nodes,origin,destination,onChange}:{nodes:NetNode[];origin:string;destination:string;onChange:()=>void}){
 const [rows,setRows]=useState<Service[]>([]),[days,setDays]=useState([0,1,2,3,4]),[time,setTime]=useState("18:00"),[cutoff,setCutoff]=useState(30),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let alive=true;api.services().then(r=>{if(alive)setRows(r.services)}).catch(e=>{if(alive)setError(String(e))});return()=>{alive=false}},[]);
 const name=(id:string)=>nodes.find(n=>n.id===id)?.name??id;
 async function save(){setBusy(true);setError("");try{await api.saveService({origin,destination,weekdays:days,departure_time:time,timezone:"Europe/Berlin",cutoff_minutes:cutoff});setRows((await api.services()).services);onChange()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);try{await api.deleteService(id);setRows(r=>r.filter(s=>s.id!==id));onChange()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <details className="card compact-settings" open><summary>Departure schedules <span className="mini">{rows.length} configured</span></summary><p>Optional user-entered services. The cutoff is extra readiness time after handling. Carrier availability is unverified.</p>{error&&<div role="alert" className="notice notice--warn">{error}</div>}<form onSubmit={e=>{e.preventDefault();void save()}}><strong>{name(origin)} → {name(destination)}</strong><div className="service-fields"><label>Departure · Europe/Berlin<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Cutoff buffer · minutes<input type="number" required min={0} max={1440} value={cutoff} onChange={e=>setCutoff(Number(e.target.value))}/></label></div><div className="day-picker">{DAYS.map((d,i)=><button key={d} type="button" aria-pressed={days.includes(i)} onClick={()=>setDays(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}>{d}</button>)}</div><button className="btn btn--sm" disabled={busy||!days.length||origin===destination}>Add service for this connection</button></form>{rows.map(r=><div className="service-row" key={r.id}><span><b>{name(r.origin)} → {name(r.destination)}</b><small>{r.weekdays.map(d=>DAYS[d]).join(", ")} · {r.departure_time} {r.timezone} · {r.cutoff_minutes}m cutoff</small></span><button className="linkbtn" disabled={busy} onClick={()=>remove(r.id)}>Remove</button></div>)}</details>
}
